
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonneSOAPServiceService", targetNamespace = "http://wssoap.infotel.com/", wsdlLocation = "http://localhost:8080/ZClientEJBWS/PersonneSOAPService?wsdl")
public class PersonneSOAPServiceService
    extends Service
{

    private final static URL PERSONNESOAPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONNESOAPSERVICESERVICE_EXCEPTION;
    private final static QName PERSONNESOAPSERVICESERVICE_QNAME = new QName("http://wssoap.infotel.com/", "PersonneSOAPServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ZClientEJBWS/PersonneSOAPService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONNESOAPSERVICESERVICE_WSDL_LOCATION = url;
        PERSONNESOAPSERVICESERVICE_EXCEPTION = e;
    }

    public PersonneSOAPServiceService() {
        super(__getWsdlLocation(), PERSONNESOAPSERVICESERVICE_QNAME);
    }

    public PersonneSOAPServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONNESOAPSERVICESERVICE_QNAME, features);
    }

    public PersonneSOAPServiceService(URL wsdlLocation) {
        super(wsdlLocation, PERSONNESOAPSERVICESERVICE_QNAME);
    }

    public PersonneSOAPServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONNESOAPSERVICESERVICE_QNAME, features);
    }

    public PersonneSOAPServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonneSOAPServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonneSOAPService
     */
    @WebEndpoint(name = "PersonneSOAPServicePort")
    public PersonneSOAPService getPersonneSOAPServicePort() {
        return super.getPort(new QName("http://wssoap.infotel.com/", "PersonneSOAPServicePort"), PersonneSOAPService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonneSOAPService
     */
    @WebEndpoint(name = "PersonneSOAPServicePort")
    public PersonneSOAPService getPersonneSOAPServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wssoap.infotel.com/", "PersonneSOAPServicePort"), PersonneSOAPService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONNESOAPSERVICESERVICE_EXCEPTION!= null) {
            throw PERSONNESOAPSERVICESERVICE_EXCEPTION;
        }
        return PERSONNESOAPSERVICESERVICE_WSDL_LOCATION;
    }

}
