
package ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonneSOAPService", targetNamespace = "http://wssoap.infotel.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonneSOAPService {


    /**
     * 
     * @param num
     * @param nom
     * @param prenom
     * @param age
     */
    @WebMethod
    @RequestWrapper(localName = "ajouterClient", targetNamespace = "http://wssoap.infotel.com/", className = "ws.AjouterClient")
    @ResponseWrapper(localName = "ajouterClientResponse", targetNamespace = "http://wssoap.infotel.com/", className = "ws.AjouterClientResponse")
    public void ajouterClient(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "age", targetNamespace = "")
        int age,
        @WebParam(name = "num", targetNamespace = "")
        int num);

    /**
     * 
     * @param idPersonne
     * @param nom
     * @param prenom
     * @param age
     * @param numAdherent
     * @return
     *     returns ws.Client
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifierClient", targetNamespace = "http://wssoap.infotel.com/", className = "ws.ModifierClient")
    @ResponseWrapper(localName = "modifierClientResponse", targetNamespace = "http://wssoap.infotel.com/", className = "ws.ModifierClientResponse")
    public Client modifierClient(
        @WebParam(name = "idPersonne", targetNamespace = "")
        long idPersonne,
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "age", targetNamespace = "")
        int age,
        @WebParam(name = "numAdherent", targetNamespace = "")
        int numAdherent);

    /**
     * 
     * @return
     *     returns java.util.List<ws.Personne>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPersonnes", targetNamespace = "http://wssoap.infotel.com/", className = "ws.GetAllPersonnes")
    @ResponseWrapper(localName = "getAllPersonnesResponse", targetNamespace = "http://wssoap.infotel.com/", className = "ws.GetAllPersonnesResponse")
    public List<Personne> getAllPersonnes();

    /**
     * 
     * @param idVoiture
     * @return
     *     returns ws.Voiture
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVoiture", targetNamespace = "http://wssoap.infotel.com/", className = "ws.GetVoiture")
    @ResponseWrapper(localName = "getVoitureResponse", targetNamespace = "http://wssoap.infotel.com/", className = "ws.GetVoitureResponse")
    public Voiture getVoiture(
        @WebParam(name = "idVoiture", targetNamespace = "")
        long idVoiture);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ws.Voiture>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVoituresParPersonne", targetNamespace = "http://wssoap.infotel.com/", className = "ws.GetVoituresParPersonne")
    @ResponseWrapper(localName = "getVoituresParPersonneResponse", targetNamespace = "http://wssoap.infotel.com/", className = "ws.GetVoituresParPersonneResponse")
    public List<Voiture> getVoituresParPersonne(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param idVoiture
     */
    @WebMethod
    @RequestWrapper(localName = "supprimerVoiture", targetNamespace = "http://wssoap.infotel.com/", className = "ws.SupprimerVoiture")
    @ResponseWrapper(localName = "supprimerVoitureResponse", targetNamespace = "http://wssoap.infotel.com/", className = "ws.SupprimerVoitureResponse")
    public void supprimerVoiture(
        @WebParam(name = "idVoiture", targetNamespace = "")
        long idVoiture);

    /**
     * 
     * @param idPersonne
     * @param marque
     */
    @WebMethod
    @RequestWrapper(localName = "ajouterVoiture", targetNamespace = "http://wssoap.infotel.com/", className = "ws.AjouterVoiture")
    @ResponseWrapper(localName = "ajouterVoitureResponse", targetNamespace = "http://wssoap.infotel.com/", className = "ws.AjouterVoitureResponse")
    public void ajouterVoiture(
        @WebParam(name = "marque", targetNamespace = "")
        String marque,
        @WebParam(name = "idPersonne", targetNamespace = "")
        long idPersonne);

    /**
     * 
     * @param idPersonne
     * @param adresse
     * @param nom
     * @param prenom
     * @param age
     * @return
     *     returns ws.Prestataire
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifierPrestataire", targetNamespace = "http://wssoap.infotel.com/", className = "ws.ModifierPrestataire")
    @ResponseWrapper(localName = "modifierPrestataireResponse", targetNamespace = "http://wssoap.infotel.com/", className = "ws.ModifierPrestataireResponse")
    public Prestataire modifierPrestataire(
        @WebParam(name = "idPersonne", targetNamespace = "")
        long idPersonne,
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "age", targetNamespace = "")
        int age,
        @WebParam(name = "adresse", targetNamespace = "")
        String adresse);

    /**
     * 
     * @param idPersonne
     * @param idVoiture
     * @param marque
     * @return
     *     returns ws.Voiture
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifierVoiture", targetNamespace = "http://wssoap.infotel.com/", className = "ws.ModifierVoiture")
    @ResponseWrapper(localName = "modifierVoitureResponse", targetNamespace = "http://wssoap.infotel.com/", className = "ws.ModifierVoitureResponse")
    public Voiture modifierVoiture(
        @WebParam(name = "idVoiture", targetNamespace = "")
        long idVoiture,
        @WebParam(name = "marque", targetNamespace = "")
        String marque,
        @WebParam(name = "idPersonne", targetNamespace = "")
        long idPersonne);

    /**
     * 
     * @return
     *     returns java.util.List<ws.Voiture>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllVoitures", targetNamespace = "http://wssoap.infotel.com/", className = "ws.GetAllVoitures")
    @ResponseWrapper(localName = "getAllVoituresResponse", targetNamespace = "http://wssoap.infotel.com/", className = "ws.GetAllVoituresResponse")
    public List<Voiture> getAllVoitures();

    /**
     * 
     * @param adresse
     * @param nom
     * @param prenom
     * @param age
     */
    @WebMethod
    @RequestWrapper(localName = "ajouterPrestataire", targetNamespace = "http://wssoap.infotel.com/", className = "ws.AjouterPrestataire")
    @ResponseWrapper(localName = "ajouterPrestataireResponse", targetNamespace = "http://wssoap.infotel.com/", className = "ws.AjouterPrestataireResponse")
    public void ajouterPrestataire(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "age", targetNamespace = "")
        int age,
        @WebParam(name = "adresse", targetNamespace = "")
        String adresse);

    /**
     * 
     * @param idPersonne
     */
    @WebMethod
    @RequestWrapper(localName = "supprimerPersonne", targetNamespace = "http://wssoap.infotel.com/", className = "ws.SupprimerPersonne")
    @ResponseWrapper(localName = "supprimerPersonneResponse", targetNamespace = "http://wssoap.infotel.com/", className = "ws.SupprimerPersonneResponse")
    public void supprimerPersonne(
        @WebParam(name = "idPersonne", targetNamespace = "")
        long idPersonne);

    /**
     * 
     * @param idPersonne
     * @return
     *     returns ws.Personne
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonne", targetNamespace = "http://wssoap.infotel.com/", className = "ws.GetPersonne")
    @ResponseWrapper(localName = "getPersonneResponse", targetNamespace = "http://wssoap.infotel.com/", className = "ws.GetPersonneResponse")
    public Personne getPersonne(
        @WebParam(name = "idPersonne", targetNamespace = "")
        long idPersonne);

}
